version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      vitest:
        patterns:
          - "vitest"
          - "@cloudflare/vitest-pool-workers"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
